[package]
name = "d24"
version = "0.1.0"
authors = ["Emre Ã‡elikten <emre@celikten.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
